name: Release

on:
  push:
    tags:
    - "v*.*.*"
    # branches: [master]

env:
  plugin_name: plugin_name

jobs:
  release:
    name: create dist
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: npm install, build, and test
      run: |
        npm ci
        npm run dist
      env:
        CI: true
    - run : echo "::set-env name=DIST_VERSION::$(echo ${{ github.ref }} | sed -E 's/^refs\/tags\/v?(.*)$/\1/')"
    - run : echo ${DIST_VERSION}
    - run : echo $DIST_VERSION
    - run : echo ${{ env.DIST_VERSION }}
    - run : echo ${{ env.plugin_name }}-v${{ env.DIST_VERSION }}.zip

    - name: create release
      id: create_release
      if: startsWith(env.DIST_VERSION, '^[0-9]+\.[0-9]+\.[0-9]$')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset
      if: startsWith(env.DIST_VERSION, '^[0-9]+\.[0-9]+\.[0-9]$')
      uses: actions/create-release@v1
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/distfile.zip
        asset_name: ${{ env.plugin_name }}-v${{ env.DIST_VERSION }}.zip
        asset_content_type: application/zip
