name: Test

on:
  push:
    branches:
    - "develop"
    - "master"

env:
  plugin_name: plugin_name

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: npm ci
    - run: npm run dist
    - run: ls

  ls:
    name: ls
    runs-on: ubuntu-latest
    steps:
    - run: ls
